// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBhvcvGNDwbdJcvmD4VLLGjZWv8qVOuG4',
    appId: '1:40753152622:web:55e116c44112996b169c7f',
    messagingSenderId: '40753152622',
    projectId: 'shopping-list-95ee9',
    authDomain: 'shopping-list-95ee9.firebaseapp.com',
    storageBucket: 'shopping-list-95ee9.firebasestorage.app',
    measurementId: 'G-6BP72KBT3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlKBAXmJQU59gjLbX_r1MLCKHfNKKDYf8',
    appId: '1:40753152622:android:b9ea52cc2a000fab169c7f',
    messagingSenderId: '40753152622',
    projectId: 'shopping-list-95ee9',
    storageBucket: 'shopping-list-95ee9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkxH9-O7hqF-L4yd3RjkAZcaBiXiHcq6U',
    appId: '1:40753152622:ios:5caba1e265259c46169c7f',
    messagingSenderId: '40753152622',
    projectId: 'shopping-list-95ee9',
    storageBucket: 'shopping-list-95ee9.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkxH9-O7hqF-L4yd3RjkAZcaBiXiHcq6U',
    appId: '1:40753152622:ios:5caba1e265259c46169c7f',
    messagingSenderId: '40753152622',
    projectId: 'shopping-list-95ee9',
    storageBucket: 'shopping-list-95ee9.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBhvcvGNDwbdJcvmD4VLLGjZWv8qVOuG4',
    appId: '1:40753152622:web:76b9cd8f548b4b79169c7f',
    messagingSenderId: '40753152622',
    projectId: 'shopping-list-95ee9',
    authDomain: 'shopping-list-95ee9.firebaseapp.com',
    storageBucket: 'shopping-list-95ee9.firebasestorage.app',
    measurementId: 'G-9F9BHGDXS0',
  );
}
